name: parser
version: 1.0.0
description: Parser for Dart for Harmonic 
author: Montana Mendy <montana@getprowl.com>
homepage: http://montanamendy.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  discord:
    git:
      url: git://github.com/Montana/parser.git
      ref: indev
  args:
  yaml:
  archive:
